In [2]:
import numpy as np

# EXERCISE 1

## 2

In [3]:
arr1 = np.zeros(10)
arr1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 3

In [3]:
arr2 = np.arange(0, 50)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [15]:
arr_el_size = arr2.itemsize

In [19]:
arr_type = arr2[0].dtype

In [17]:
arr_size = arr2[0].itemsize * 50

In [20]:
print(f'"{arr_size}" is list size with element size = {arr_el_size} for items elements of {arr_type} ')

"200" is list size with element size = 4 for items elements of int32 


# 4

In [30]:
np.info(np. add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

## 5

In [24]:
arr5 = np.arange(10, 50)
arr5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 6

In [25]:
arr5_rev = arr5[::-1]
arr5_rev

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## 7

In [29]:
arr7 = np.arange(0,9).reshape(3, 3)
arr7

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 8

In [34]:
arr8 = np.array([1,2,0,0,4,0])
not_0 = np.nonzero(arr8)
not_0

(array([0, 1, 4], dtype=int64),)

## 9

In [35]:
arr9 = np.eye(3)
arr9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# 10

In [97]:
arr10 = np.full((5,5), np.arange(0,5, dtype = 'float'))
arr10

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

# 11

In [70]:
arr11 = np.linspace(0, 1, 12)[1:-1]
arr11

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

# 12

In [61]:
arr12 = np.random.rand(1, 1, 10)
arr12

array([[[0.53665184, 0.2669819 , 0.1675873 , 0.11660008, 0.6896671 ,
         0.33396205, 0.5849341 , 0.42305755, 0.33879697, 0.13232198]]])

In [62]:
np.sort(arr12)

array([[[0.11660008, 0.13232198, 0.1675873 , 0.2669819 , 0.33396205,
         0.33879697, 0.42305755, 0.53665184, 0.5849341 , 0.6896671 ]]])

# 13

In [77]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min, end = " ")
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min, end = " ")
   print(np.finfo(dtype).max)

-128 127
-2147483648 2147483647
-9223372036854775808 9223372036854775807
-3.4028235e+38 3.4028235e+38
-1.7976931348623157e+308 1.7976931348623157e+308


# 14

In [80]:
arr14_float = np.arange(10, dtype = 'float32')
arr14

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [87]:
arr14_int = arr14_float.astype('int32')
arr14_int.dtype

dtype('int32')

# 15

In [90]:
arr15 = np.random.randint(1, 10, 15).reshape(3, 5)
arr15

array([[4, 1, 8, 6, 4],
       [2, 3, 4, 2, 3],
       [6, 6, 4, 8, 4]])

In [99]:
res15 = np.mean(arr15, axis=1)
res15

array([4.6, 2.8, 5.6])

# 16

In [100]:
arr16 = np.random.randint(1, 10, 15).reshape(3, 5)
arr16

array([[3, 7, 2, 7, 5],
       [8, 1, 3, 3, 7],
       [8, 7, 5, 1, 2]])

In [113]:
res16 = arr16[arr16[:,1].argsort()]
res16

array([[8, 1, 3, 3, 7],
       [3, 7, 2, 7, 5],
       [8, 7, 5, 1, 2]])

# 17

In [114]:
arr17 = np.random.randint(1, 10, 15).reshape(3, 5)
arr17

array([[1, 3, 6, 4, 6],
       [3, 6, 4, 2, 2],
       [5, 9, 1, 8, 5]])

In [121]:
arr17[[2, 0]] = arr17[[0, 2]]
arr17

array([[5, 9, 1, 8, 5],
       [3, 6, 4, 2, 2],
       [1, 3, 6, 4, 6]])

# 18

In [124]:
np.repeat([0, 1, 2], [2, 3, 1])

array([0, 0, 1, 1, 1, 2])