In [1]:
import numpy as np

# 1

In [2]:
array1 = np.arange(10, 21)

In [3]:
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

# 2

In [8]:
array1.ndim

1

In [5]:
array1.shape

(11,)

In [6]:
array1.size

11

In [7]:
array1.dtype

dtype('int32')

# 3

In [9]:
array2 = np.arange(10, 21).astype('float16')
array2

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
      dtype=float16)

In [10]:
array2.dtype

dtype('float16')

In [12]:
int_array2 = array2.astype('int32')
int_array2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
int_array2.dtype

dtype('int32')

# 4

In [16]:
double_array = np.multiply(int_array2, 2)
double_array

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40])