In [2]:
import numpy as np

# 1

In [3]:
arr1 = np.arange(20, 31)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

# 2

In [4]:
arr2 = np.arange(10, 21, 2)
arr2

array([10, 12, 14, 16, 18, 20])

# 3

In [5]:
arr3 = np.linspace(0, 1, 5)
arr3

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

# 4

In [21]:
arr4 = np.random.rand(3)
arr4

array([0.65853292, 0.36535053, 0.52948433])

# 5

In [17]:
arr5 = np.random.randint(1, 11, 4)
arr5

array([ 8,  5,  8, 10])