In [1]:
import numpy as np

# 1

In [2]:
array1 = np.arange(10, 21)
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
array1[3]

13

# 2

In [5]:
#array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [18]:
array2_1dim = np.arange(1, 10)
array2_1dim

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
array2_2dim = array2_1dim.reshape(3, 3)
array2_2dim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
array2_2dim[1, 2]

6

# 3

In [13]:
array3 = np.arange(0, 10)
array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
array3[2:6]

array([2, 3, 4, 5])

# 4

In [17]:
array4 = np.arange(1, 10)
array4 = array2_1dim.reshape(3, 3)
array4


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
array4[:2, -2:]

array([[2, 3],
       [5, 6]])