In [1]:
import numpy as np

In [9]:
two_dim_array = np.arange(0, 25)

In [10]:
two_dim_array = two_dim_array.reshape(5, 5)
two_dim_array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [4]:
two_dim_array.mean(axis = 1)

array([ 2.,  7., 12., 17., 22.])

In [5]:
two_dim_array.mean(axis = 0)

array([10., 11., 12., 13., 14.])

In [6]:
two_dim_array = two_dim_array.argsort()
two_dim_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [7]:
two_dim_array

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]], dtype=int64)

In [11]:
two_dim_array[[0, 1]] = two_dim_array[[1, 0]]
two_dim_array

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])