In [1]:
import numpy as np

In [2]:
one_dim_array = np.arange(11)

In [3]:
one_dim_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
one_dim_array[0]

0

In [5]:
one_dim_array[-1]

10

In [8]:
one_dim_array[2::2]

array([ 2,  4,  6,  8, 10])

## 2 dim array

In [10]:
two_dim_array = np.arange(10)
two_dim_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
two_dim_array = two_dim_array.reshape((5, 2))

In [16]:
two_dim_array[1]

array([2, 3])

In [17]:
two_dim_array[1:3]

array([[2, 3],
       [4, 5]])

In [18]:
two_dim_array[1:3, 0]

array([2, 4])

In [19]:
two_dim_array[::-1]

array([[8, 9],
       [6, 7],
       [4, 5],
       [2, 3],
       [0, 1]])

In [20]:
two_dim_array[ ::-1, ::-2]

array([[9],
       [7],
       [5],
       [3],
       [1]])