# INTRO

In [4]:
import numpy as np

In [5]:
array = np.array([1, 2, 3, 4, 5]) #numpy array

In [6]:
array

array([1, 2, 3, 4, 5])

In [7]:
array2 = np.array([1, 2, 3, 4, 5])

In [8]:
array * array2

array([ 1,  4,  9, 16, 25])

## Numpy array attributes

In [9]:
array.ndim #number of dimensions

1

In [10]:
two_dim_array = np.array([[1, 2, 3, 4, 5], [1, 2, 3, 4, 5], [1, 2, 3, 4, 5]])

In [11]:
two_dim_array

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [12]:
two_dim_array.ndim

2

In [13]:
# shape - amount of  rows/columns
array.shape

(5,)

In [14]:
two_dim_array.shape

(3, 5)

In [15]:
two_dim_array.size

15

In [16]:
#data type
two_dim_array.dtype

dtype('int32')

In [18]:
# converting to diff type
float_array = array.astype('float16')

In [19]:
float_array

array([1., 2., 3., 4., 5.], dtype=float16)

## creating arrays

In [20]:
my_array = np.arange(1, 10)

In [21]:
my_array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])